name: Terraform PR
on:
  pull_request:
    paths: ["envs/**", "modules/**"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_DEV }}
          aws-region: eu-west-3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"
      - run: terraform fmt -check -recursive
        working-directory: .
      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -no-color -out=tfplan
